export default theme = {
  colors: {
    WHITE: '#ffffff',
    PLACE_HOLDER_TEXT_COLOR: '#c9c9c9',
    GREY: 'grey',
    GREY2: '#aaa',
    GREY3: '#ccc',
    GREY4: '#e9e9e9',
    WHITE_FADE: 'rgba(255, 255, 255, 0.6)',
    BLACK: '#000',
    PRIMARY_BLUE: '#39abee',
    BACKGROUND_COLOR: '#EEEFF1',
    BLUE: '#0079B8',
    ORANGE: '#BE5400',
    GREEN: '#185007',
    RED: '#DF2401',
    RED_DASHBOARD: '#a02100',
    PURPLE: '#4D0B79',
    GREY: 'grey',
    GREY2: '#aaa',
    GREY3: '#ccc',
  },
  fontFamily: {
    comfortaa: {
      bold: 'Comfortaa-Bold',
      light: 'Comfortaa-Light',
      regular: 'Comfortaa-Regular',
      semi_bold: 'Comfortaa-SemiBold',
      medium: 'Comfortaa-medium',
    },
  },
  fontSize: {
    EXTRA_SMALL: 10,
    SMALL: 12,
    NORMAL: 14,
    MEDIUM: 16,
    HEADING: 18,
    LARGE: 20,
    MEDIUM_LARGE: 22,
    EXTRA_LARGE: 24,
    TITLE: 34,
  },
};
